Fix message when AuxTel pointing components exists. (+23 squashed commits) Squashed commits: [9f80b4e] Update yum install of OpenSpliceDDS so it will aways install the latest revision. [24d1e4e] remove step 1 from building develop-env [f73bf76] run scons on packages that still needs it. [a44461a] Updated develop-env build steps to use pytest. [5cc7e68] Create an extra stop to pull the images on salobj build rerun failed tests . [e67c7e9] User pytest instead of py.test [3df73bc] Run salobj unit tests with no color. [3a1163f] pip install pytest-subtest instead of conda install. [5c68945] no need to install setuptools. [5d1ba21] Update rotator container with latest ts_hexrotcomm. [9902167] Tryin to solve breakage by ignoring conda update. [95d5769] Separate each package installation in an individual step. [f43741e] Adds pytest-subtests to develop-env. Cleaning conda env is broken so ignore it. Stop using scons and start using py.test to run unit tests on all packages. [1008a1d] Add mt-rotator and mtptg to list of CSCs on kafka_producers. Deploy mt-rotator simulator. Deploy mtptg [d97466d] Fix IP. [6465809] Fix ip address. [dd18f18] Fix develop folder map for user containers. [b379e22] Add notebook servers for Sandrine and Austin. [d593d12] Update atptg container. [fd8beeb] DM-22130: Deploy SAL 4/SalObj 5 in Tucson Test Stand
 - Modify build script for ATHexapod.
 - Add linear stage to kafka writers.
 - Finishing updating build and deployment of all available components on the Tucson Test Stand.
 - Add Dockerfile for FiberSpectrograph.
 - Add a kafka producer for FiberSpectrograph (missing for previous producers).
 - Add Fiber Spectrograph deployment configuration.
 - Deploy ATPtg
 - Deploy atspectrograph
 - Update users notebook servers.
[ebb04a9] Update pointing component build scripts.
[cd4f78e] Update users notebook servers.
[a50ff4c] Build and Deployment of Tucson Test Stand components.

Starting with those that  use the develop-env directly and kafka producers.

Update atptg container.

Add notebook servers for Sandrine and Austin.

Fix develop folder map for user containers.

Fix ip address.

Fix IP.

Add mt-rotator and mtptg to list of CSCs on kafka_producers.
Deploy mt-rotator simulator.
Deploy mtptg

Adds pytest-subtests to develop-env.
Cleaning conda env is broken so ignore it.
Stop using scons and start using py.test to run unit tests on all packages.

Separate each package installation in an individual step.

Tryin to solve breakage by ignoring conda update.

Update rotator container with latest ts_hexrotcomm.

no need to install setuptools.

pip install pytest-subtest instead of conda install.

Run salobj unit tests with no color.

User pytest instead of py.test

Create an extra stop to pull the images on salobj build
rerun failed tests .

Updated develop-env build steps to use pytest.

run scons on packages that still needs it.

remove step 1 from building develop-env

Update yum install of OpenSpliceDDS so it will aways install the latest revision.

Fix message when AuxTel pointing components exists.

diff --git a/rotator/Dockerfile b/rotator/Dockerfile
--- a/rotator/Dockerfile
+++ b/rotator/Dockerfile
@@ -1,4 +1,4 @@
-FROM lsstts/develop-env:sal_v4.0.0RC1_salobj_v5.0.0RC2_xml_v4.3.0RC1_idl_v0.4.0RC2
+FROM lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0
 
 LABEL maintainer Tiago Ribeiro <tribeiro@lsst.org>
 
@@ -8,17 +8,11 @@ WORKDIR /home/saluser/repos
 RUN git clone https://github.com/lsst-ts/ts_rotator.git && \
     git clone https://github.com/lsst-ts/ts_hexrotcomm.git
 
-WORKDIR /home/saluser/repos/ts_xml
-RUN git fetch --all && git checkout "tickets/DM-21694"
-
 WORKDIR /home/saluser/repos/ts_rotator
-RUN git fetch --all && git checkout "tickets/DM-21694"
+RUN git fetch --all && git checkout "tags/v0.1.0" -b "v0.1.0"
 
 WORKDIR /home/saluser/repos/ts_hexrotcomm
-RUN git fetch --all && git checkout "tickets/DM-21694"
-
-WORKDIR /home/saluser/repos/ts_idl
-RUN git fetch --all && git checkout "tickets/DM-21694"
+RUN git fetch --all && git checkout "tags/v0.1.0" -b "v0.1.1"
 
 WORKDIR /home/saluser
 RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
@@ -29,17 +23,19 @@ RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
 WORKDIR /home/saluser/repos/ts_hexrotcomm
 RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     source /home/saluser/repos/ts_sal/setup.env && \
+    setup ts_salobj -t current && \
     eups declare -r . -t current && setup ts_hexrotcomm -t current && \
     scons
 
 WORKDIR /home/saluser/repos/ts_rotator
 RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     source /home/saluser/repos/ts_sal/setup.env && \
+    setup ts_salobj -t current && \
     eups declare -r . -t current && setup ts_rotator -t current && \
-    scons
+    scons || echo "Failed, ignoring"
 
 WORKDIR /home/saluser/
-#COPY setup.sh /home/saluser/.setup.sh
+COPY setup.sh /home/saluser/.setup.sh
 
 ENTRYPOINT ["/bin/bash", "--"]
 CMD ["/home/saluser/.setup.sh"]
