Changes for the big-bang.

diff --git a/queue-env/Dockerfile b/queue-env/Dockerfile
--- a/queue-env/Dockerfile
+++ b/queue-env/Dockerfile
@@ -38,41 +38,44 @@ RUN yum -y --enablerepo=extras install epel-release \
 USER saluser
 WORKDIR /home/saluser
 
-RUN source /opt/lsst/software/stack/loadLSST.bash
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib &&\
+    conda install -y ipython jupyter jupyterlab tornado=4.5.3 jinja2 scipy ephem gitpython && \
+    conda update -y pyqt fontconfig sqlalchemy && \
+    cd ../ && \
+    python -c 'import matplotlib.pyplot' && \
+    conda clean -ay && pip install "documenteer[pipelines]==0.4.2"
 
 RUN mkdir repos
 
 WORKDIR /home/saluser/repos
-RUN git clone https://github.com/lsst-ts/ts_opensplice.git
+RUN git clone https://github.com/lsst-ts/ts_opensplice.git && \
+git clone https://github.com/lsst-ts/ts_sal.git && \
+git clone https://github.com/lsst-ts/ts_salobj.git && \
+git clone https://github.com/lsst-ts/ts_scriptqueue.git && \
+git clone https://github.com/lsst-ts/ts_xml.git
 
-WORKDIR /home/saluser/repos
-RUN git clone https://github.com/lsst-ts/ts_sal.git
 WORKDIR /home/saluser/repos/ts_sal
-RUN git checkout "tags/v3.8.31" -b "v3.8.31"
+RUN git fetch && git checkout "tags/v3.8.41" -b "v3.8.41"
 
-WORKDIR /home/saluser/repos
-RUN git clone https://github.com/lsst-ts/salobj.git
-WORKDIR /home/saluser/repos/salobj
-RUN git fetch && git checkout "tags/3.0.0" -b "3.0.0"
+WORKDIR /home/saluser/repos/ts_salobj
+RUN git fetch && git checkout "tags/v3.6.1" -b "v3.6.1"
 
-WORKDIR /home/saluser/repos
-RUN git clone https://github.com/lsst-ts/ts_scriptqueue.git
 WORKDIR /home/saluser/repos/ts_scriptqueue
-RUN git checkout "tags/0.2.0" -b "0.2.0"
+RUN git fetch && git checkout "tags/v1.0.1" -b "v1.0.1"
 
-WORKDIR /home/saluser/repos
-RUN git clone https://github.com/lsst-ts/ts_xml.git
 WORKDIR /home/saluser/repos/ts_xml
 # RUN git checkout "tags/v3.8.31" -b "v3.8.31"
-RUN git checkout a2db54e64b1d19489cf5c05ff19fc4659293b933 -b "v3.8.31.1"
-RUN cp sal_interfaces/SALGenerics.xml /home/saluser/repos/ts_sal/test/ && \
-cp sal_interfaces/SALSubsystems.xml /home/saluser/repos/ts_sal/test/ && \
-cp sal_interfaces/Test/*.xml /home/saluser/repos/ts_sal/test/ && \
-cp sal_interfaces/Script/*.xml /home/saluser/repos/ts_sal/test/ && \
-cp sal_interfaces/ScriptQueue/*.xml /home/saluser/repos/ts_sal/test/ && \
-cp sal_interfaces/CBP/*.xml /home/saluser/repos/ts_sal/test/
+RUN git fetch && git checkout "tags/v3.8.41" -b "v3.8.41"
+#RUN cp sal_interfaces/SALGenerics.xml /home/saluser/repos/ts_sal/test/ && \
+#cp sal_interfaces/SALSubsystems.xml /home/saluser/repos/ts_sal/test/ && \
+#cp sal_interfaces/Test/*.xml /home/saluser/repos/ts_sal/test/ && \
+#cp sal_interfaces/Script/*.xml /home/saluser/repos/ts_sal/test/ && \
+#cp sal_interfaces/ScriptQueue/*.xml /home/saluser/repos/ts_sal/test/ && \
+#cp sal_interfaces/CBP/*.xml /home/saluser/repos/ts_sal/test/
 
 WORKDIR /home/saluser
+
+RUN source /opt/lsst/software/stack/loadLSST.bash && pip install --upgrade pycodestyle
 
 ENV LSST_SDK_INSTALL=/home/saluser/repos/ts_sal
 ENV OSPL_HOME=/home/saluser/repos/ts_opensplice/OpenSpliceDDS/V6.4.1/HDE/x86_64.linux
@@ -80,16 +83,44 @@ ENV PYTHON_BUILD_VERSION=3.6m
 ENV PYTHON_BUILD_LOCATION=/opt/lsst/software/stack/python/miniconda3-4.3.21/
 ENV LSST_DDS_DOMAIN=citest
 
-COPY setup.sh /home/saluser/setup.sh
-COPY setup_and_build.sh /home/saluser/.setup_and_build.sh
+WORKDIR /home/saluser/repos/ts_xml
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && eups declare -r . ts_xml -t $USER
 
-RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib &&\
-    conda install -y ipython jupyter jupyterlab tornado=4.5.3 jinja2 scipy ephem gitpython && \
-    conda update -y pyqt fontconfig sqlalchemy && \
-    cd ../ && \
-    python -c 'import matplotlib.pyplot' && \
-    conda clean -ay
+WORKDIR /home/saluser/repos/ts_sal
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    source /home/saluser/repos/ts_sal/setup.env && \
+    eups declare -r . ts_sal -t $USER && \
+    setup ts_sal -t $USER && \
+    mkdir -p $SAL_WORK_DIR && \
+    mkdir -p $TS_SAL_DIR/lib &&\
+    scons && \
+    make_salpy_libs.py Script && \
+    make_salpy_libs.py ScriptQueue
+
+WORKDIR /home/saluser/repos/ts_salobj
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    source /home/saluser/repos/ts_sal/setup.env && \
+    setup ts_sal -t $USER && \
+    eups declare -r . ts_salobj -t $USER && setup ts_salobj -t $USER && scons
+
+WORKDIR /home/saluser/repos/ts_scriptqueue
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    source /home/saluser/repos/ts_sal/setup.env && \
+    setup ts_sal -t $USER && \
+    setup ts_salobj -t $USER && \
+    eups declare -r . ts_scriptqueue -t $USER && setup ts_scriptqueue -t $USER
+    #scons || echo "ts_scriptqueue: Failed scons"
+
+WORKDIR /home/saluser/
+COPY setup.sh /home/saluser/.setup.sh
+
+#COPY setup_and_build.sh /home/saluser/.setup_and_build.sh
+#COPY setup2.sh /home/saluser/setup_alternative.sh
+#COPY setup_dds.env /home/saluser/setup_dds.env
 
 #RUN pip install ipython
 #RUN pip install jupyter
-RUN echo "echo source setup.sh to startupt" >> ~/.bashrc
+#RUN echo "echo source setup.sh to startupt" >> ~/.bashrc
+
+ENTRYPOINT ["/bin/bash", "--"]
+CMD ["/home/saluser/.setup.sh"]
