Add at_dome dockerfile. Change ataos to use ticket branch and checkout tag on config attcs Add salobj4 develop-env dockerfile Add DIMM dockerfile. Add ATPtg config file

diff --git a/develop-env/develop_py36/salobj_4/Dockerfile b/develop-env/develop_py36/salobj_4/Dockerfile
--- a/develop-env/develop_py36/salobj_4/Dockerfile
+++ b/develop-env/develop_py36/salobj_4/Dockerfile
@@ -75,28 +75,40 @@ RUN  git clone https://github.com/lsst-ts/ts_config_ocs.git && \
      git clone https://github.com/lsst-ts/ts_xml.git && \
      git clone https://github.com/lsst-ts/ts_standardscripts.git && \
      git clone https://github.com/lsst-ts/ts_externalscripts.git && \
+     git clone https://github.com/lsst-ts/ts_ATMCSSimulator.git && \
      git clone https://github.com/lsst-ts/ts_ATDome.git && \
      git clone https://github.com/lsst-ts/ts_ATDomeTrajectory.git && \
      git clone https://github.com/lsst-ts/ts_idl.git
+
+
 
 WORKDIR /home/saluser/repos/ts_sal
 RUN git fetch && git checkout "tags/v3.10.0" -b "v3.10.0"
 
 WORKDIR /home/saluser/repos/ts_salobj
-RUN git fetch && git checkout "tags/v3.12.0" -b "v3.12.0"
+RUN git fetch --tags && git checkout "tags/v4.1.0" -b "v4.1.0"
 
 WORKDIR /home/saluser/repos/ts_scriptqueue
-RUN git fetch && git checkout "tags/v1.4.1" -b "v1.4.1"
+RUN git fetch --tags && git checkout "tags/v2.1.0" -b "v2.1.0"
 
 WORKDIR /home/saluser/repos/ts_xml
 # RUN git fetch && git checkout develop && git pull
 RUN git fetch --tags && git tag -n && git checkout "tags/v3.10.0" -b "v3.10.0"
 
 WORKDIR /home/saluser/repos/ts_config_ocs
-RUN git fetch && git checkout "develop"
+RUN git fetch --tags && git checkout "tags/v0.0-alpha.0" -b "v0.0-alpha.0"
 
 WORKDIR /home/saluser/repos/ts_config_attcs
-RUN git fetch && git checkout "develop"
+RUN git fetch --tags && git checkout "tags/v0.1-alpha.4" -b "v0.1-alpha.4"
+
+WORKDIR /home/saluser/repos/ts_ATMCSSimulator
+RUN git fetch --tags && git checkout "tags/v0.6.0" -b "v0.6.0"
+
+WORKDIR /home/saluser/repos/ts_standardscripts
+RUN git fetch --tags && git checkout "tags/v0.2.0" -b "v0.2.0"
+
+WORKDIR /home/saluser/repos/ts_externalscripts
+RUN git fetch --tags && git checkout "tags/v0.1.0" -b "v0.1.0"
 
 WORKDIR /home/saluser
 
@@ -150,44 +162,35 @@ RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     mkdir -p $SAL_WORK_DIR && \
     mkdir -p $TS_SAL_DIR/lib && scons
 
+WORKDIR /home/saluser/repos/ts_idl
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    source /home/saluser/repos/ts_sal/setup.env && \
+    setup ts_sal -t current && \
+    eups declare -r . ts_idl -t current && setup ts_idl -t current && scons
+
 WORKDIR /home/saluser/repos/ts_salobj
 RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     source /home/saluser/repos/ts_sal/setup.env && \
     setup ts_sal -t current && \
+    setup ts_idl -t current && \
+    make_idl_files.py Test && \
     eups declare -r . ts_salobj -t current && setup ts_salobj -t current && scons
-
-WORKDIR /home/saluser/repos/ts_scriptqueue
-RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
-    source /home/saluser/repos/ts_sal/setup.env && \
-    setup ts_sal -t current && \
-    setup ts_salobj -t current && \
-    make_salpy_libs.py ScriptQueue && \
-    eups declare -r . ts_scriptqueue -t current && setup ts_scriptqueue -t current && \
-    scons
-
-# || echo Building scriptqueue failed. IGNORING...
 
 WORKDIR /home/saluser/repos/ts_ATDome
 RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     source /home/saluser/repos/ts_sal/setup.env && \
     setup ts_salobj -t current && \
     setup ts_config_attcs -t current && \
-    make_salpy_libs.py ATDome && \
+    make_idl_files.py ATDome && \
     eups declare -r . ts_ATDome -t current && setup ts_ATDome -t current && scons
 
 WORKDIR /home/saluser/repos/ts_ATDomeTrajectory
 RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     source /home/saluser/repos/ts_sal/setup.env && \
     setup ts_salobj -t current && \
-    make_salpy_libs.py ATMCS ATDomeTrajectory && \
+    make_idl_files.py ATMCS ATDomeTrajectory && \
     setup ts_config_attcs -t current && \
     eups declare -r . ts_ATDomeTrajectory -t current && setup ts_ATDomeTrajectory -t current && scons
-
-WORKDIR /home/saluser/repos/
-RUN git clone https://github.com/lsst-ts/ts_ATMCSSimulator.git
-
-WORKDIR /home/saluser/repos/ts_ATMCSSimulator
-RUN git fetch && git checkout "v0.4.0" -b "v0.4.0"
 
 WORKDIR /home/saluser/repos/ts_ATMCSSimulator
 RUN  source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
@@ -198,15 +201,36 @@ RUN  source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     setup ts_ATMCSSimulator -t current && \
     scons
 
+WORKDIR /home/saluser/repos/ts_scriptqueue
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    eups declare -r . ts_scriptqueue -t current
+
 WORKDIR /home/saluser/repos/ts_standardscripts
-RUN git fetch && git checkout "tags/v0.1.0" -b "v0.1.0"
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    eups declare -r . ts_standardscripts -t current
+
+WORKDIR /home/saluser/repos/ts_externalscripts
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    eups declare -r . ts_externalscripts -t current
+
+# || echo Building standard script failed. IGNORING...
+
+WORKDIR /home/saluser/repos/ts_scriptqueue
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    source /home/saluser/repos/ts_sal/setup.env && \
+    setup ts_sal -t current && \
+    setup ts_idl -t current && \
+    setup ts_salobj -t current && \
+    make_idl_files.py ScriptQueue && \
+    setup ts_scriptqueue -t current && \
+    scons || echo Building standard script failed. IGNORING...
+
+WORKDIR /home/saluser/repos/ts_standardscripts
 RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     source /home/saluser/repos/ts_sal/setup.env && \
     setup ts_sal -t current && \
     setup ts_salobj -t current && \
-    setup ts_scriptqueue -t current && \
-    make_salpy_libs.py Electrometer ATPtg ATCamera ATMonochromator ATSpectrograph FiberSpectrograph&& \
-    eups declare -r . ts_standardscripts -t current && \
+    make_idl_files.py Electrometer ATPtg ATCamera ATMonochromator ATSpectrograph FiberSpectrograph && \
     setup ts_config_attcs -t current && \
     setup ts_config_ocs -t current && \
     setup ts_ATMCSSimulator -t current && \
@@ -222,9 +246,23 @@ RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
     setup ts_standardscripts -t current && \
     setup ts_config_attcs -t current && \
     setup ts_config_ocs -t current && \
-    eups declare -r . ts_externalscripts -t current && \
     setup ts_externalscripts -t current && \
-    scons || echo Building external script failed. IGNORING...
+    scons || echo Building standard script failed. IGNORING...
+
+WORKDIR /home/saluser/repos/ts_scriptqueue
+RUN source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && \
+    source /home/saluser/repos/ts_sal/setup.env && \
+    setup ts_sal -t current && \
+    setup ts_idl -t current && \
+    setup ts_salobj -t current && \
+    make_idl_files.py ScriptQueue Script && \
+    setup ts_scriptqueue -t current && \
+    scons
+
+# || echo Building external script failed. IGNORING...
+
+# || echo Building scriptqueue failed. IGNORING...
+
 
 WORKDIR /home/saluser/
 COPY setup.sh /home/saluser/.setup.sh
